# Site settings
title: Głównie JavaScript
email: jcubic@jcubic.pl
description: "Blog Głównie JavaScript - informacje najczęściej na temat Front-Endu, głównie o języku JavaScript, ale także na temat nowych api HTML5 czy CSS."
baseurl: ""
url: "http://jcubic.pl"

exclude:
    -
        README.md

include:
    -
        .htaccess

users:
    jcubic:
        url: "http://jakub.jankiewi.cz"
        name: "Jakub T. Jankiewicz"

paginate: 10

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title.html
kramdown:
    input: GFM
gems: [jekyll-paginate]
